parameters:
#    raa_admin.example.class: RAA\AdminBundle\Example

services:
#    raa_admin.example:
#        class: %raa_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
